version: '3.3'

networks:
  workmotion-db-network:
    driver: bridge
 
services:
  mysql-workmotion:
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=workmotion
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306
    networks:
      - workmotion-db-network
    container_name: mysql-workmotion
    healthcheck:
            test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
            timeout: 20s
            retries: 15
  workmotion:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: workmotion
    networks:
      - workmotion-db-network
    depends_on:
      mysql-workmotion:
        condition: service_healthy # depending on the healthcheck test
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    image: workmotion:0.1
